# @package _global_

defaults:
  - _self_
  - data: stanford_cars # choose datamodule with `test_dataloader()` for evaluation
  - model: clip_dotf
  - callbacks: default_eval
  - logger:
      - wandb
      - csv
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - optional slurm:

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default.yaml

task_name: "eval"

tags: ["dev"]

comment: ""

# passing checkpoint path is necessary for evaluation
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 2016
